apiVersion: v1
kind: ConfigMap
metadata:
  name: cpa-manage-api-config
  namespace: wumitech-cpa
data:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-Xms512m -Xmx2048m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

