apiVersion: v1
kind: Service
metadata:
  name: cpa-manage-api
  namespace: wumitech-cpa
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http  
  selector:
    app: cpa-manage-api

